name: Runnnnn

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Which environment to deploy to"
        required: true
        type: environment

jobs:
  run-postman-collection:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install Newman
        run: npm install -g newman

      - name: Install html-extra reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Make directory for result
        run: mkdir -p testResult
       
      - name: Download Postman environment
    run: |
        curl -s "https://api.getpostman.com/environments/${{ vars.ENV_ID }}" \
        -H "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
        -o env.json

       - name: Run Postman Collection
    run: |
      newman run "https://api.getpostman.com/collections/1911365-1a4e032c-530f-422a-a669-ab37949cbc15?apikey=${{ secrets.POSTMAN_API_KEY }}" \
      -e env.json \
      -r cli,htmlextra \
      --reporter-htmlextra-export testResult/report.html

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: testResult
